//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Position { get; set; }
        public int TeamId { get; set; }
        public int CountryId { get; set; }
        public Nullable<decimal> MonthlyWage { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Team Team { get; set; }
    }
}
